version: "3"

services:
  grpc_server:
    build:
      context: ./GrpcProductServer
      dockerfile: Dockerfile
    container_name: server_app
    ports:
      - "5001:80"
    networks:
      - grpc_network

  grpc_client:
    build:
      context: ./GrpcProductClient
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "5000:80"
    environment:
      GrpcAddress: http://grpc_server
    networks:
      - grpc_network

networks:
  grpc_network:
